/*
 * drv_gpio.c
 *
 *  Created on: 1 kwi 2016
 *      Author: lucja
 */
#include "platform_cfg.h"

const PIN_t PIN_LED0 		= { LED0_GPIO, { .Pin=LED0_PIN, .Mode=GPIO_MODE_OUTPUT_PP, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_LED1 		= { LED1_GPIO, { .Pin=LED1_PIN, .Mode=GPIO_MODE_OUTPUT_PP, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_BEEP 		= { BEEP_GPIO, { .Pin=BEEP_PIN, .Mode=GPIO_MODE_OUTPUT_PP, .Speed=GPIO_SPEED_FREQ_LOW }};

const PIN_t PIN_BARO_XCLR 	= { BARO_XCLR_GPIO, { .Pin=BARO_XCLR_PIN, .Mode=GPIO_MODE_OUTPUT_PP, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_BARO_EOC 	= { BARO_EOC_GPIO, { .Pin=BARO_EOC_PIN, .Mode=GPIO_MODE_INPUT, .Pull=GPIO_NOPULL , .Speed=GPIO_SPEED_FREQ_LOW }};

const PIN_t PIN_USARTx_RX	= { USARTx_RX_GPIO, { .Pin=USARTx_RX_PIN, .Mode=GPIO_MODE_INPUT, .Pull =GPIO_PULLUP, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_USARTx_TX	= { USARTx_TX_GPIO, { .Pin=USARTx_TX_PIN, .Mode=GPIO_MODE_AF_PP, .Speed=GPIO_SPEED_FREQ_LOW }};

const PIN_t PIN_I2Cx_SCL	= { I2Cx_SCL_GPIO, { .Pin=I2Cx_SCL_PIN, .Mode=GPIO_MODE_AF_OD, .Pull=GPIO_PULLUP, .Speed=GPIO_SPEED_FREQ_HIGH }};
const PIN_t PIN_I2Cx_SDA	= { I2Cx_SDA_GPIO, { .Pin=I2Cx_SDA_PIN, .Mode=GPIO_MODE_AF_OD, .Pull=GPIO_PULLUP, .Speed=GPIO_SPEED_FREQ_HIGH }};

const PIN_t PIN_MPU_INT 	= { MPU_INT_GPIO, { .Pin=MPU_INT_PIN, .Mode=GPIO_MODE_IT_RISING, .Pull=GPIO_PULLUP, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_MAG_RDRY 	= { MAG_RDRY_GPIO, { .Pin=MAG_RDRY_PIN, .Mode=GPIO_MODE_IT_FALLING, .Pull=GPIO_PULLUP, .Speed=GPIO_SPEED_FREQ_LOW }};

const PIN_t PIN_PWMO1	 	= { PWMO12_GPIO, { .Pin=PWMO1_PIN, .Mode=GPIO_MODE_AF_PP, .Speed=GPIO_SPEED_LOW }};
const PIN_t PIN_PWMO2	 	= { PWMO12_GPIO, { .Pin=PWMO2_PIN, .Mode=GPIO_MODE_AF_PP, .Speed=GPIO_SPEED_LOW }};
const PIN_t PIN_PWMO3	 	= { PWMO36_GPIO, { .Pin=PWMO3_PIN, .Mode=GPIO_MODE_OUTPUT_PP, .Speed=GPIO_SPEED_LOW }};
const PIN_t PIN_PWMO4	 	= { PWMO36_GPIO, { .Pin=PWMO4_PIN, .Mode=GPIO_MODE_AF_PP, .Speed=GPIO_SPEED_LOW }};
const PIN_t PIN_PWMO5	 	= { PWMO36_GPIO, { .Pin=PWMO5_PIN, .Mode=GPIO_MODE_OUTPUT_PP, .Speed=GPIO_SPEED_LOW }};
const PIN_t PIN_PWMO6	 	= { PWMO36_GPIO, { .Pin=PWMO6_PIN, .Mode=GPIO_MODE_AF_PP, .Speed=GPIO_SPEED_LOW }};

const PIN_t PIN_PWMI1 		= { PWMI14_GPIO, { .Pin=PWMI1_PIN, .Mode=GPIO_MODE_INPUT, .Pull=GPIO_PULLDOWN, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_PWMI2 		= { PWMI14_GPIO, { .Pin=PWMI2_PIN, .Mode=GPIO_MODE_INPUT, .Pull=GPIO_PULLDOWN, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_PWMI3 		= { PWMI14_GPIO, { .Pin=PWMI3_PIN, .Mode=GPIO_MODE_INPUT, .Pull=GPIO_PULLDOWN, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_PWMI4 		= { PWMI14_GPIO, { .Pin=PWMI4_PIN, .Mode=GPIO_MODE_INPUT, .Pull=GPIO_PULLDOWN, .Speed=GPIO_SPEED_FREQ_LOW }};

const PIN_t PIN_PWMI5 		= { PWMI56_GPIO, { .Pin=PWMI5_PIN, .Mode=GPIO_MODE_OUTPUT_PP, .Pull=GPIO_PULLDOWN, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_PWMI6 		= { PWMI56_GPIO, { .Pin=PWMI6_PIN, .Mode=GPIO_MODE_OUTPUT_PP, .Pull=GPIO_PULLDOWN, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_PWMI7 		= { PWMI78_GPIO, { .Pin=PWMI7_PIN, .Mode=GPIO_MODE_OUTPUT_PP, .Pull=GPIO_PULLDOWN, .Speed=GPIO_SPEED_FREQ_LOW }};
const PIN_t PIN_PWMI8 		= { PWMI78_GPIO, { .Pin=PWMI8_PIN, .Mode=GPIO_MODE_OUTPUT_PP, .Pull=GPIO_PULLDOWN, .Speed=GPIO_SPEED_FREQ_LOW }};

HAL_StatusTypeDef gpioInit( void )
{
	/* LED */
	LED0_GPIO_CLK_ENABLE();
	LED1_GPIO_CLK_ENABLE();
	HAL_GPIO_Init( PIN_LED0.gpio, (GPIO_InitTypeDef*)&PIN_LED0.cfg );
	HAL_GPIO_Init( PIN_LED1.gpio, (GPIO_InitTypeDef*)&PIN_LED1.cfg );

	LEDOff( PIN_LED0 );
	LEDOff( PIN_LED1 );

	/* IO */

	PWMI56_CLK_ENABLE();
	PWMI78_CLK_ENABLE();
	HAL_GPIO_Init( PIN_PWMI5.gpio, (GPIO_InitTypeDef*)&PIN_PWMI5.cfg );
	HAL_GPIO_Init( PIN_PWMI6.gpio, (GPIO_InitTypeDef*)&PIN_PWMI6.cfg );
	HAL_GPIO_Init( PIN_PWMI7.gpio, (GPIO_InitTypeDef*)&PIN_PWMI7.cfg );
	HAL_GPIO_Init( PIN_PWMI8.gpio, (GPIO_InitTypeDef*)&PIN_PWMI8.cfg );

	return HAL_OK;
};
